spring:
  application:
    name: order-provider
server:
  port: 5555

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #eureka.instance.prefer-ip-address  表示将自己的IP注册到Eureka Server上，
  #如果不配置,会将当前服务提供者所在的主机名注册到Eureka Server上。
  instance:
    prefer-ip-address: true
  cloud:
    circuit:
      breaker:
        enabled: true
  http:
    encoding:
      charset: UTF-8
      force: true
      force-request: true
      force-response: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream